version: '3.9'
services:
  external-task:
    build: /
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - my-network
  camunda:
    image: camunda/camunda-bpm-platform:7.20.0
    restart: always
    ports:
      - '8080:8080'
    expose:
      - '8080'
    networks:
      - my-network
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27017:27017'
    expose:
      - '27017'
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh admin -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - my-network
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    expose:
      - '8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
